version: '3'
services:
  postgres:
    container_name: postgres_db
    image: bosch_postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./store:/var/lib/postgresql/data
    ports:
      - 5432:5432
