version: '3'
services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./store:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
